# SPDX-License-Identifier: Apache-2.0

set(TRICORE_C_FLAGS)
list(APPEND TRICORE_C_FLAGS -mcpu=${GCC_M_CPU})

list(APPEND TOOLCHAIN_C_FLAGS ${TRICORE_C_FLAGS})
list(APPEND TOOLCHAIN_LD_FLAGS ${TRICORE_C_FLAGS})
